### ISSUE TITLE
Zattoo HiQ 1.3 rebuilding database

### ISSUE THREAD

**Issue by elijahbailey** [rolapp/plugin.video.zattooHiQ#11]
I did reinstalling the addon multiple times. When rebuildiung the database the following error occurs:
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'source' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.zattooHiQ/plugin.py", line 957, in <module>
                                                main()
                                              File "/home/osmc/.kodi/addons/plugin.video.zattooHiQ/plugin.py", line 861, in main
                                                _keymap_.toggleKeyMap()
                                              File "/home/osmc/.kodi/addons/plugin.video.zattooHiQ/resources/keymap.py", line 268, in toggleKeyMap
                                                with open(source, 'r') as file: content = file.read()
                                            UnboundLocalError: local variable 'source' referenced before assignment
                                            -->End of Python script error report<--

checked the line in keymap.py and found a missing "else:" path or a missing default setting of the variable source.
This error also prevents the addon from playing tv.

**Comment by rolapp** [comment]
Is fixed on v1.3.1


Am 6. September 2017 16:09:27 schrieb elijahbailey <notifications@github.com>:

**Comment by elijahbailey** [comment]
Thanks
