### ISSUE TITLE
Unable to load channels information at start

### ISSUE THREAD

**Issue by sabbane** [rolapp/plugin.video.zattooHiQ#3]
OS: Android 6 (Android TV Box)
Kodi: v16.1

By starting Kodi the application crashes. The following entry is added to the logfile:
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'PopUp' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.zattooHiQ/service.py", line 96, in <module>
                                                if __addon__.getSetting('dbonstart') == 'true': start()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.zattooHiQ/service.py", line 63, in start
                                                _zattooDB_.cleanProg()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.zattooHiQ/resources/zattooDB.py", line 536, in cleanProg
                                                PopUp.close()
                                            UnboundLocalError: local variable 'PopUp' referenced before assignment
                                            -->End of Python script error report<--`

**Comment by rolapp** [comment]
Thank you for report the Bug
